## Merging

In [1]:
import pandas as pd
import numpy as np

np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
df1 = pd.DataFrame(np.arange(16).reshape(4,4), columns=list("ABCD"))
df1

A   B   C   D
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [10]:
df2 = pd.DataFrame(np.zeros((3,4)), columns= list("ABCD"))
df2

A    B    C    D
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [11]:
df3 = pd.DataFrame(np.ones((4,3)), index = [1,5,10,15])
df3

0    1    2
1   1.0  1.0  1.0
5   1.0  1.0  1.0
10  1.0  1.0  1.0
15  1.0  1.0  1.0

--
## Concat
- concatenates pandas objects along an axis (rows, colums)
- there are set logics


In [13]:
df1, df2

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
      A    B    C    D
 0  0.0  0.0  0.0  0.0
 1  0.0  0.0  0.0  0.0
 2  0.0  0.0  0.0  0.0)

In [14]:
pd.concat([df1, df2], axis = 0) #axis=0 default

A     B     C     D
0   0.0   1.0   2.0   3.0
1   4.0   5.0   6.0   7.0
2   8.0   9.0  10.0  11.0
3  12.0  13.0  14.0  15.0
0   0.0   0.0   0.0   0.0
1   0.0   0.0   0.0   0.0
2   0.0   0.0   0.0   0.0

In [16]:
#puts all cols from df1 and then all cols from df2
# those indices that are missing in one df 
pd.concat([df1,df2], axis="columns")

A   B   C   D    A    B    C    D
0   0   1   2   3  0.0  0.0  0.0  0.0
1   4   5   6   7  0.0  0.0  0.0  0.0
2   8   9  10  11  0.0  0.0  0.0  0.0
3  12  13  14  15  NaN  NaN  NaN  NaN

In [18]:
df1, df3

(    A   B   C   D
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15,
       0    1    2
 1   1.0  1.0  1.0
 5   1.0  1.0  1.0
 10  1.0  1.0  1.0
 15  1.0  1.0  1.0)

In [23]:
#concatenates in axis rows, df1 rows first then df2 rows, NANs are used for missing values
pd.concat([df1, df3], axis='rows')

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  NaN  NaN  NaN
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
1    NaN   NaN   NaN   NaN  1.0  1.0  1.0
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [21]:
# per default outer joint
pd.concat([df1, df3], axis='columns')

A     B     C     D    0    1    2
0    0.0   1.0   2.0   3.0  NaN  NaN  NaN
1    4.0   5.0   6.0   7.0  1.0  1.0  1.0
2    8.0   9.0  10.0  11.0  NaN  NaN  NaN
3   12.0  13.0  14.0  15.0  NaN  NaN  NaN
5    NaN   NaN   NaN   NaN  1.0  1.0  1.0
10   NaN   NaN   NaN   NaN  1.0  1.0  1.0
15   NaN   NaN   NaN   NaN  1.0  1.0  1.0

In [22]:
# intersection between df1 and df2 on the indices
pd.concat([df1, df3], axis='columns', join="inner")

A  B  C  D    0    1    2
1  4  5  6  7  1.0  1.0  1.0

## Merge

In [25]:
left = pd.DataFrame(
    {
        "key": ["K0", "K0", "K1", "K2"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)
left, right

(  key   A   B
 0  K0  A0  B0
 1  K0  A1  B1
 2  K1  A2  B2
 3  K2  A3  B3,
   key   C   D
 0  K0  C0  D0
 1  K1  C1  D1
 2  K2  C2  D2
 3  K3  C3  D3)

In [28]:
#k3 not included -> k3 from right not included i.e inner joint
pd.merge(left, right, on="key", indicator=True)

key   A   B   C   D _merge
0  K0  A0  B0  C0  D0   both
1  K0  A1  B1  C0  D0   both
2  K1  A2  B2  C1  D1   both
3  K2  A3  B3  C2  D2   both

In [29]:
# syntax with method
left.merge(right, on="key", indicator=True)

key   A   B   C   D _merge
0  K0  A0  B0  C0  D0   both
1  K0  A1  B1  C0  D0   both
2  K1  A2  B2  C1  D1   both
3  K2  A3  B3  C2  D2   both

In [30]:
# note that left does not have a k3
# so in row index 4 onöly merge from right
# outer join -> unioin between left and right
left.merge(right, on="key",how="outer", indicator=True)

key    A    B   C   D      _merge
0  K0   A0   B0  C0  D0        both
1  K0   A1   B1  C0  D0        both
2  K1   A2   B2  C1  D1        both
3  K2   A3   B3  C2  D2        both
4  K3  NaN  NaN  C3  D3  right_only

In [31]:

right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

# new example

In [32]:
left = pd.DataFrame(
    {
        "key1": ["K0", "K0", "K1", "K2"],
        "key2": ["K0", "K1", "K0", "K1"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
    }
)

right = pd.DataFrame(
    {
        "key1": ["K0", "K1", "K1", "K2"],
        "key2": ["K0", "K0", "K0", "K0"],
        "A": ["A0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    }
)
left, right

(  key1 key2   A   B
 0   K0   K0  A0  B0
 1   K0   K1  A1  B1
 2   K1   K0  A2  B2
 3   K2   K1  A3  B3,
   key1 key2   A   D
 0   K0   K0  A0  D0
 1   K1   K0  C1  D1
 2   K1   K0  C2  D2
 3   K2   K0  C3  D3)

In [34]:
#merge on both key1 and key2 columns, and an inner join - intersection
left.merge(right, on=["key1", "key2"], indicator=True)

key1 key2 A_x   B A_y   D _merge
0   K0   K0  A0  B0  A0  D0   both
1   K1   K0  A2  B2  C1  D1   both
2   K1   K0  A2  B2  C2  D2   both

In [35]:
#A_x left and A_y is right
left.merge(right, on=["key1", "key2"], indicator=True, how="left")

key1 key2 A_x   B  A_y    D     _merge
0   K0   K0  A0  B0   A0   D0       both
1   K0   K1  A1  B1  NaN  NaN  left_only
2   K1   K0  A2  B2   C1   D1       both
3   K1   K0  A2  B2   C2   D2       both
4   K2   K1  A3  B3  NaN  NaN  left_only

In [36]:
left.merge(right, on=["key1", "key2"], indicator=True, how="right")

key1 key2  A_x    B A_y   D      _merge
0   K0   K0   A0   B0  A0  D0        both
1   K1   K0   A2   B2  C1  D1        both
2   K1   K0   A2   B2  C2  D2        both
3   K2   K0  NaN  NaN  C3  D3  right_only

## Join
- uses merge internally
- combines columns

In [38]:
left = pd.DataFrame(
    {"A": ["A0", "A1", "A2"], "B": ["B0", "B1", "B2"]}, index=["K0", "K1", "K2"]
)


right = pd.DataFrame(
    {"C": ["C0", "C2", "C3"], "D": ["D0", "D2", "D3"]}, index=["K0", "K2", "K3"]
)
left, right

(     A   B
 K0  A0  B0
 K1  A1  B1
 K2  A2  B2,
      C   D
 K0  C0  D0
 K2  C2  D2
 K3  C3  D3)

In [40]:
# note we join on k1 which only exists in left -> so this is a left join
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [41]:
# indices from right -> right join
left.join(right, how="right")

A    B   C   D
K0   A0   B0  C0  D0
K2   A2   B2  C2  D2
K3  NaN  NaN  C3  D3

# Webscraping HTML tables

In [3]:
import pandas as pd 
fifa_tables = pd.read_html("https://en.wikipedia.org/wiki/FIFA")

In [4]:
len(fifa_tables)

31

In [5]:
type(fifa_tables)

list

In [7]:
fifa_tables[0].head()

0  \
0  Fédération internationale de Football Associat...   
1                                               Logo   
2  Map of the members of FIFA according to their ...   
3                                       Abbreviation   
4                                            Founded   

                                                   1  
0  Fédération internationale de Football Associat...  
1                                               Logo  
2  Map of the members of FIFA according to their ...  
3                                            FIFA[1]  
4                         21 May 1904; 118 years ago

In [8]:
fifa_tables[1]

Unnamed: 0                   Unnamed: 1
0         NaN                          NaN
1         Use                        Sport
2  Proportion                          3:5
3     Adopted                         2018
4      Design  Blue field with a FIFA logo

In [10]:
fifa_tables[2].head()

No.                               Name         Country      Took office  \
0   1                      Robert Guérin          France      23 May 1904   
1   2             Daniel Burley Woolfall  United Kingdom      4 June 1906   
2   —  Cornelis August Wilhelm Hirschman     Netherlands  24 October 1918   
3   3                        Jules Rimet          France     1 March 1921   
4   4               Rodolphe Seeldrayers         Belgium     21 June 1954   

       Left office            Note  
0      4 June 1906             NaN  
1  24 October 1918  Died in office  
2             1920          Acting  
3     21 June 1954             NaN  
4   7 October 1955  Died in office

In [11]:
title_holders = pd.read_html("https://en.wikipedia.org/wiki/FIFA", match="Runners-up")
title_holders

[                                                    0                       1  \
 0                                         Competition                     NaN   
 1                                      National teams          National teams   
 2                                      FIFA World Cup                     NaN   
 3            Men's Olympic Football Tournament (U-23)                     NaN   
 4                                 FIFA U-20 World Cup                     NaN   
 5                                 FIFA U-17 World Cup                     NaN   
 6                               FIFA Futsal World Cup                     NaN   
 7        Men's Youth Olympic Futsal Tournament (U-20)                     NaN   
 8          FIFA Beach Soccer World Cup (see the BSWW)                     NaN   
 9   FIFA Arab Cup (senior teams of the UAFA (Arab ...                     NaN   
 10                             National teams (women)  National teams (women)   
 11             

In [12]:
len(title_holders)

1

In [13]:
title_holders[0].head()

0               1               2  \
0                               Competition             NaN            Year   
1                            National teams  National teams  National teams   
2                            FIFA World Cup             NaN    2018 (Final)   
3  Men's Olympic Football Tournament (U-23)             NaN    2020 (Final)   
4                       FIFA U-20 World Cup             NaN    2019 (Final)   

                3               4               5               6  \
0       Champions           Title      Runners-up             NaN   
1  National teams  National teams  National teams  National teams   
2          France             2nd         Croatia             NaN   
3          Brazil             2nd           Spain             NaN   
4         Ukraine             1st     South Korea             NaN   

                  7  
0  Next edition[55]  
1    National teams  
2      2022 (Final)  
3      2024 (Final)  
4      2023 (Final)

In [17]:
pd.read_html("https://en.wikipedia.org/wiki/FIFA", match="Runners-up", header=0)[0].head()

Competition      Unnamed: 1            Year  \
0                            National teams  National teams  National teams   
1                            FIFA World Cup             NaN    2018 (Final)   
2  Men's Olympic Football Tournament (U-23)             NaN    2020 (Final)   
3                       FIFA U-20 World Cup             NaN    2019 (Final)   
4                       FIFA U-17 World Cup             NaN    2019 (Final)   

        Champions           Title      Runners-up      Unnamed: 6  \
0  National teams  National teams  National teams  National teams   
1          France             2nd         Croatia             NaN   
2          Brazil             2nd           Spain             NaN   
3         Ukraine             1st     South Korea             NaN   
4          Brazil             4th          Mexico             NaN   

  Next edition[55]  
0   National teams  
1     2022 (Final)  
2     2024 (Final)  
3     2023 (Final)  
4     2023 (Final)